# Generated by Django 3.2.5 on 2021-07-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NEWS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NEWS_TITLE', models.CharField(blank=True, max_length=150, null=True, verbose_name='NEWS_TITLE')),
                ('NEWS_SUBTITLE', models.TextField(blank=True, null=True, verbose_name='NEWS_SUBTITLE')),
                ('NEWS_LINK', models.TextField(blank=True, null=True, verbose_name='NEWS_LINK')),
                ('NEWS_SOURCE', models.CharField(blank=True, max_length=150, null=True, verbose_name='NEWS_TITLE')),
                ('POST_CREATED_AT', models.DateTimeField(auto_now_add=True, null=True, verbose_name='TIME_STAMP')),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
    ]
