# Generated by Django 3.2.5 on 2021-07-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorboSeshApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='NEWS_SOURCE',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='NEWS_SOURCE'),
        ),
        migrations.AlterField(
            model_name='news',
            name='POST_CREATED_AT',
            field=models.TextField(default=2, verbose_name='TIME_STAMP'),
            preserve_default=False,
        ),
    ]
